server:
  port: 8081
spring:
  cloud:
    gateway:
      routes:
        - id: sw-interface
          uri: http://localhost:8082
          predicates:
            - Path=/api/**
dubbo:
  application:
    name: gateway-service
    logger: slf4j
    qos-port: 33333
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848?username=nacos&password=nacos